spring:
  application:
    name: images-combiner

  h2:
    datasource:
      url: jdbc:h2:mem:sgapp
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true